select * FROM books_staging ORDER BY title_norm;

UPDATE books_staging
SET
  isbn10     = NULLIF(TRIM(isbn10), ''),
  isbn13     = NULLIF(TRIM(isbn13), ''),
  title_norm = NULLIF(TRIM(title_norm), ''),
  book_uid   = NULLIF(TRIM(book_uid), ''),
  author_1_role = NULLIF(TRIM(author_1_role), ''),
  author_2_role = NULLIF(TRIM(author_2_role), ''),
  author_3_role = NULLIF(TRIM(author_3_role), ''),
  author_4_role = NULLIF(TRIM(author_4_role), ''),
  author_5_role = NULLIF(TRIM(author_5_role), ''),
  language = NULLIF(TRIM(language), ''),
  series_name_norm = NULLIF(TRIM(series_name_norm), ''),
  series_num = NULLIF(TRIM(series_num), ''),
  description_norm = NULLIF(TRIM(description_norm), ''),
  pages_norm = NULLIF(TRIM(pages_norm), '')


/*-----------------------------------------------*/
/* AUTHOR TABLE */
/*-----------------------------------------------*/

/*
CREATE TABLE IF NOT EXISTS author (
	author_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name TEXT,
    first_name TEXT,
    middle_name TEXT,
    last_name TEXT
);


WITH author_full_name AS (
  SELECT DISTINCT author_name
  FROM (
    SELECT primary_author_name AS author_name FROM books_staging
    UNION
    SELECT author_2 FROM books_staging
    UNION
    SELECT author_3 FROM books_staging
    UNION
    SELECT author_4 FROM books_staging
    UNION
    SELECT author_5 FROM books_staging
  ) all_authors
  WHERE author_name IS NOT NULL AND author_name <> ''
),
prep AS (
  SELECT
    author_name,
    regexp_split_to_array(trim(regexp_replace(author_name, '\s+', ' ', 'g')), ' ') AS parts
  FROM author_full_name
),
parsed AS (
  SELECT
    author_name,
  -- first: token 1, letters only, empty -> NULL
  NULLIF(regexp_replace(parts[1], '[^A-Za-z]', '', 'g'), '') AS first_name,
  -- last: only if 2+ tokens, letters only, empty -> NULL
  CASE
    WHEN array_length(parts, 1) >= 2
    THEN NULLIF(regexp_replace(parts[array_length(parts,1)], '[^A-Za-z]', '', 'g'), '')
  END AS last_name,
  -- middle: only if 3+ tokens, keep spaces between, non-letters removed, empty -> NULL
  CASE
    WHEN array_length(parts, 1) >= 3
    THEN NULLIF(
      regexp_replace(array_to_string(parts[2:array_length(parts,1)-1], ' '), '[^A-Za-z ]', '', 'g'),
      ''
    )
  END AS middle_name
  FROM prep
),
insert_into_table AS (
  INSERT INTO author (full_name, first_name, middle_name, last_name)
  SELECT
    parsed.author_name,
    parsed.first_name,
    parsed.middle_name,
    parsed.last_name
  FROM parsed 
  WHERE NOT EXISTS (
    SELECT 1
    FROM author 
    WHERE author.full_name = parsed.author_name
  )
  RETURNING author_id
)
SELECT *
FROM insert_into_table;
*/

SELECT * FROM author;
SELECT count(*) FROM author;




/*-----------------------------------------------*/
/* Language Table */
/*-----------------------------------------------*/

/*
CREATE TABLE IF NOT EXISTS language (
	language_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    language TEXT UNIQUE
);

SELECT DISTINCT LANGUAGE FROM books_staging;

INSERT INTO language (language)
SELECT DISTINCT LANGUAGE FROM books_staging
ON CONFLICT (language) DO NOTHING;	

*/

SELECT * FROM LANGUAGE;


/*-----------------------------------------------*/
/* seperate genre column
-- This will make it easier when we need to make genre tables */
/*-----------------------------------------------*/
/*
ALTER TABLE books_staging
ADD COLUMN genre_1 TEXT,
ADD COLUMN genre_2 TEXT,
ADD COLUMN genre_3 TEXT,
ADD COLUMN genre_4 TEXT,
ADD COLUMN genre_5 TEXT,
ADD COLUMN genre_6 TEXT,
ADD COLUMN genre_7 TEXT,
ADD COLUMN genre_8 TEXT,
ADD COLUMN genre_9 TEXT,
ADD COLUMN genre_10 TEXT;


UPDATE books_staging
SET 
    genre_1 = NULLIF(TRIM(BOTH '''' FROM split_part(
        TRIM(BOTH '[]' FROM REPLACE(genres_norm, '''', '')), 
        ',', 1)), ''),
    genre_2 = NULLIF(TRIM(BOTH '''' FROM split_part(
        TRIM(BOTH '[]' FROM REPLACE(genres_norm, '''', '')), 
        ',', 2)), ''),
    genre_3 = NULLIF(TRIM(BOTH '''' FROM split_part(
        TRIM(BOTH '[]' FROM REPLACE(genres_norm, '''', '')), 
        ',', 3)), ''),
    genre_4 = NULLIF(TRIM(BOTH '''' FROM split_part(
        TRIM(BOTH '[]' FROM REPLACE(genres_norm, '''', '')), 
        ',', 4)), ''),
    genre_5 = NULLIF(TRIM(BOTH '''' FROM split_part(
        TRIM(BOTH '[]' FROM REPLACE(genres_norm, '''', '')), 
        ',', 5)), ''),
    genre_6 = NULLIF(TRIM(BOTH '''' FROM split_part(
        TRIM(BOTH '[]' FROM REPLACE(genres_norm, '''', '')), 
        ',', 6)), ''),
    genre_7 = NULLIF(TRIM(BOTH '''' FROM split_part(
        TRIM(BOTH '[]' FROM REPLACE(genres_norm, '''', '')), 
        ',', 7)), ''),
    genre_8 = NULLIF(TRIM(BOTH '''' FROM split_part(
        TRIM(BOTH '[]' FROM REPLACE(genres_norm, '''', '')), 
        ',', 8)), ''),
    genre_9 = NULLIF(TRIM(BOTH '''' FROM split_part(
        TRIM(BOTH '[]' FROM REPLACE(genres_norm, '''', '')), 
        ',', 9)), ''),
    genre_10 = NULLIF(TRIM(BOTH '''' FROM split_part(
        TRIM(BOTH '[]' FROM REPLACE(genres_norm, '''', '')), 
        ',', 10)), '');
        


UPDATE books_staging
SET 
    genre_1 = REPLACE(genre_1, '"', ''),
    genre_2 = REPLACE(genre_2, '"', ''),
    genre_3 = REPLACE(genre_3, '"', ''),
    genre_4 = REPLACE(genre_4, '"', ''),
    genre_5 = REPLACE(genre_5, '"', ''),
    genre_6 = REPLACE(genre_6, '"', ''),
    genre_7 = REPLACE(genre_7, '"', ''),
    genre_8 = REPLACE(genre_8, '"', ''),
    genre_9 = REPLACE(genre_9, '"', ''),
    genre_10 = REPLACE(genre_10, '"', '');
*/


-- check
SELECT 
    genres_norm,
    genre_1,
    genre_2,
    genre_3,
    genre_4,
    genre_5,
    genre_6,
    genre_7,
    genre_8,
    genre_9,
    genre_10
FROM books_staging

SELECT 
    COUNT(*) FILTER (WHERE genre_1 IS NOT NULL) as has_genre_1,
    COUNT(*) FILTER (WHERE genre_2 IS NOT NULL) as has_genre_2,
    COUNT(*) FILTER (WHERE genre_3 IS NOT NULL) as has_genre_3,
    COUNT(*) FILTER (WHERE genre_4 IS NOT NULL) as has_genre_4,
    COUNT(*) FILTER (WHERE genre_5 IS NOT NULL) as has_genre_5,
    COUNT(*) FILTER (WHERE genre_6 IS NOT NULL) as has_genre_6,
    COUNT(*) FILTER (WHERE genre_7 IS NOT NULL) as has_genre_7,
    COUNT(*) FILTER (WHERE genre_8 IS NOT NULL) as has_genre_8,
    COUNT(*) FILTER (WHERE genre_9 IS NOT NULL) as has_genre_9,
    COUNT(*) FILTER (WHERE genre_10 IS NOT NULL) as has_genre_10
FROM books_staging;


/*-----------------------------------------------*/
/* genre table */ 
/*-----------------------------------------------*/

/*

CREATE TABLE IF NOT EXISTS genre (
	genre_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    genre TEXT UNIQUE
);

INSERT INTO genre (genre)
SELECT DISTINCT genre
FROM (
    SELECT genre_1 AS genre FROM books_staging
    UNION
    SELECT genre_2 FROM books_staging
    UNION
    SELECT genre_3 FROM books_staging
    UNION
    SELECT genre_4 FROM books_staging
    UNION
    SELECT genre_5 FROM books_staging
    UNION
    SELECT genre_6 FROM books_staging
    UNION
    SELECT genre_7 FROM books_staging
    UNION
    SELECT genre_8 FROM books_staging
    UNION
    SELECT genre_9 FROM books_staging
    UNION
    SELECT genre_10 FROM books_staging
) all_genres
WHERE genre IS NOT NULL
ON CONFLICT (genre) DO NOTHING;

*/

select * FROM genre;


/*-----------------------------------------------*/
/* Role */
/*-----------------------------------------------*/

/*
CREATE TABLE IF NOT EXISTS role (
	role_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    role TEXT UNIQUE
);

INSERT INTO role (role)
SELECT role
FROM (
    SELECT author_1_role AS role FROM books_staging
    UNION
    SELECT author_2_role FROM books_staging
    UNION
    SELECT author_3_role FROM books_staging
    UNION
    SELECT author_4_role FROM books_staging
    UNION
    SELECT author_5_role FROM books_staging
) roles
WHERE role IS NOT NULL
ON CONFLICT (role) DO NOTHING; -- prevents duplicate inserts safely.
*/
		
SELECT * FROM ROLE;		

/*-----------------------------------------------*/
/* Publisher */
/*-----------------------------------------------*/

/*
CREATE TABLE IF NOT EXISTS publisher (
	publisher_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    publisher TEXT UNIQUE
);

SELECT * FROM publisher;

INSERT INTO publisher (publisher)
SELECT DISTINCT publisher_norm 
FROM books_staging
WHERE publisher_norm IS NOT NULL
  AND TRIM(publisher_norm) != ''
ON CONFLICT (publisher) DO NOTHING;
*/

SELECT * FROM publisher order BY publisher_id;


/*-----------------------------------------------*/
/* Edition */
/*-----------------------------------------------*/
/*
UPDATE books_staging
SET edition_norm = NULL
WHERE edition_norm IS NOT NULL 
  AND TRIM(edition_norm) = '';

CREATE TABLE IF NOT EXISTS edition (
    edition_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    edition TEXT UNIQUE NOT NULL
);


SELECT DISTINCT edition_norm
FROM books_staging
WHERE edition_norm IS NOT NULL
  AND TRIM(edition_norm) != '';
  
INSERT INTO edition (edition)
SELECT DISTINCT edition_norm
FROM books_staging
WHERE edition_norm IS NOT NULL
  AND TRIM(edition_norm) != ''
ON CONFLICT (edition) DO NOTHING;

*/

-- Verify
SELECT * FROM edition;

-- Check count
SELECT COUNT(*) FROM edition;



/*-----------------------------------------------*/
/* Format */
/*-----------------------------------------------*/

/*
CREATE TABLE IF NOT EXISTS format (
	format_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    format TEXT UNIQUE
);

INSERT INTO format (format)
SELECT DISTINCT books_staging."bookFormat_norm" FROM books_staging
WHERE books_staging."bookFormat_norm" IS NOT NULL
ON CONFLICT (format) DO NOTHING;
*/

SELECT * FROM format



/*-----------------------------------------------*/
/* Book Table */
/*-----------------------------------------------*/

/*
CREATE TABLE IF NOT EXISTS book (
	book_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT
);

SELECT book_uid::int, title_norm FROM books_staging ORDER BY book_uid; -- 35362

SELECT DISTINCT ON (book_uid) book_uid::int, title_norm
FROM books_staging
ORDER BY book_uid::int, title_norm;


INSERT INTO book (book_id, title)
SELECT DISTINCT ON (book_uid) book_uid::int, title_norm
FROM books_staging;
*/

SELECT * FROM book; -- 35,338



/*-----------------------------------------------*/
/* Series Table */
/*-----------------------------------------------*/

/*
UPDATE books_staging
SET series_name_norm = NULL
WHERE series_name_norm IS NOT NULL 
  AND TRIM(series_name_norm) = '';

-- check
SELECT series_name_norm, COUNT(*)
FROM books_staging
GROUP BY series_name_norm
ORDER BY series_name_norm;

CREATE TABLE IF NOT EXISTS series (
    series_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    series_name TEXT UNIQUE NOT NULL
);


SELECT DISTINCT series_name_norm, series_num
FROM books_staging
WHERE is_series = 'True';


INSERT INTO series (series_name)
SELECT DISTINCT series_name_norm
FROM books_staging
WHERE series_name_norm IS NOT NULL
ON CONFLICT (series_name) DO NOTHING;

*/

SELECT * FROM series;


SELECT * FROM books_staging

/*-----------------------------------------------*/
/* Cleaning dates*/
/*-----------------------------------------------*/

/*

UPDATE books_staging
SET "publishDate_norm" = NULL
WHERE "publishDate_norm" IS NOT NULL 
  AND TRIM("publishDate_norm") = '';


UPDATE books_staging
SET "firstPublishDate_norm" = NULL
WHERE "firstPublishDate_norm" IS NOT NULL 
  AND TRIM("firstPublishDate_norm") = '';


*/

SELECT 
    "publishDate_norm",
    "firstPublishDate_norm",
    COUNT(*)
FROM books_staging
GROUP BY "publishDate_norm", "firstPublishDate_norm"
ORDER BY "publishDate_norm", "firstPublishDate_norm"
LIMIT 50;

-- Check for any invalid date formats (not YYYY-MM-DD pattern)
SELECT DISTINCT "publishDate_norm"
FROM books_staging
WHERE "publishDate_norm" IS NOT NULL
  AND "publishDate_norm" !~ '^\d{4}-\d{2}-\d{2}$'
LIMIT 20;

SELECT DISTINCT "firstPublishDate_norm"
FROM books_staging
WHERE "firstPublishDate_norm" IS NOT NULL
  AND "firstPublishDate_norm" !~ '^\d{4}-\d{2}-\d{2}$'
LIMIT 20;


SELECT * FROM books_staging 

/*-----------------------------------------------*/
/* Book_ISBN */
/*-----------------------------------------------*/
/*
-- Create book_isbn table
CREATE TABLE IF NOT EXISTS book_isbn (
    book_isbn_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    isbn10 TEXT,
    isbn13 TEXT,
    book_id INT NOT NULL,
    format_id INT,
    edition_id INT,
    publisher_id INT,
    language_id INT,
    is_boxset BOOLEAN DEFAULT FALSE,
    
    CONSTRAINT fk_book
        FOREIGN KEY (book_id)
        REFERENCES book (book_id)
        ON DELETE CASCADE,
    
    CONSTRAINT fk_format
        FOREIGN KEY (format_id)
        REFERENCES format (format_id)
        ON DELETE SET NULL,
    
    CONSTRAINT fk_edition
        FOREIGN KEY (edition_id)
        REFERENCES edition (edition_id)
        ON DELETE SET NULL,
    
    CONSTRAINT fk_publisher
        FOREIGN KEY (publisher_id)
        REFERENCES publisher (publisher_id)
        ON DELETE SET NULL,
    
    CONSTRAINT fk_language
        FOREIGN KEY (language_id)
        REFERENCES language (language_id)
        ON DELETE SET NULL,
    
    CONSTRAINT uq_isbn13 UNIQUE (isbn13),
    CONSTRAINT uq_isbn10 UNIQUE (isbn10)
);


INSERT INTO book_isbn (
    isbn10,
    isbn13,
    book_id,
    format_id,
    edition_id,
    publisher_id,
    language_id,
    is_boxset
)
SELECT
    books_staging.isbn10,
    books_staging.isbn13,
    books_staging.book_uid::INT,
    format.format_id,
    edition.edition_id,
    publisher.publisher_id,
    language.language_id,
    CASE 
        WHEN books_staging.is_boxset = '1' THEN TRUE
        ELSE FALSE
    END AS is_boxset
FROM books_staging
LEFT JOIN format ON format.format = books_staging."bookFormat_norm"
LEFT JOIN edition ON edition.edition = books_staging.edition_norm
LEFT JOIN publisher ON publisher.publisher = books_staging.publisher_norm
LEFT JOIN language ON language.language = books_staging.language
WHERE books_staging.isbn10 IS NOT NULL
   OR books_staging.isbn13 IS NOT NULL;
*/
/*
ALTER TABLE book_isbn
ADD COLUMN publish_date DATE,
ADD COLUMN original_publish_date DATE;

-- Update with data from books_staging
UPDATE book_isbn
SET 
    publish_date = books_staging."publishDate_norm"::DATE,
    original_publish_date = books_staging."firstPublishDate_norm"::DATE
FROM books_staging
WHERE (book_isbn.isbn10 = books_staging.isbn10 OR book_isbn.isbn13 = books_staging.isbn13);
*/

SELECT * FROM book_isbn LIMIT 100;
SELECT * FROM book_isbn WHERE is_boxset IS TRUE;


-- Check statistics
SELECT 
    COUNT(*) as total_records,
    COUNT(isbn10) as has_isbn10,
    COUNT(isbn13) as has_isbn13,
    COUNT(format_id) as has_format,
    COUNT(edition_id) as has_edition,
    COUNT(publisher_id) as has_publisher,
    COUNT(language_id) as has_language
FROM book_isbn;



SELECT * FROM series;


/*-----------------------------------------------*/
/* Author_ISBN */
/*-----------------------------------------------*/



/*
CREATE TABLE IF NOT EXISTS author_isbn (
    author_isbn_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    book_isbn_id INT NOT NULL,
    author_id INT NOT NULL,
    role_id INT,
    
    CONSTRAINT fk_book_isbn
        FOREIGN KEY (book_isbn_id)
        REFERENCES book_isbn (book_isbn_id)
        ON DELETE CASCADE,
    
    CONSTRAINT fk_author
        FOREIGN KEY (author_id)
        REFERENCES author (author_id)
        ON DELETE CASCADE,
    
    CONSTRAINT fk_role
        FOREIGN KEY (role_id)
        REFERENCES role (role_id)
        ON DELETE SET NULL,
    
    CONSTRAINT uq_author_isbn_role UNIQUE (book_isbn_id, author_id, role_id)
);



-- Insert author 1 (primary author)
WITH author_1_data AS (
    SELECT 
        book_isbn.book_isbn_id,
        author.author_id,
        role.role_id
    FROM books_staging
    JOIN book_isbn ON (book_isbn.isbn10 = books_staging.isbn10 OR book_isbn.isbn13 = books_staging.isbn13)
    JOIN author ON author.full_name = books_staging.primary_author_name
    LEFT JOIN role ON role.role = books_staging.author_1_role
    WHERE books_staging.primary_author_name IS NOT NULL
)
INSERT INTO author_isbn (book_isbn_id, author_id, role_id)
SELECT DISTINCT book_isbn_id, author_id, role_id
FROM author_1_data;

-- Insert author 2
WITH author_2_data AS (
    SELECT 
        book_isbn.book_isbn_id,
        author.author_id,
        role.role_id
    FROM books_staging
    JOIN book_isbn ON (book_isbn.isbn10 = books_staging.isbn10 OR book_isbn.isbn13 = books_staging.isbn13)
    JOIN author ON author.full_name = books_staging.author_2
    LEFT JOIN role ON role.role = books_staging.author_2_role
    WHERE books_staging.author_2 IS NOT NULL
)
INSERT INTO author_isbn (book_isbn_id, author_id, role_id)
SELECT DISTINCT book_isbn_id, author_id, role_id
FROM author_2_data
ON CONFLICT (book_isbn_id, author_id, role_id) DO NOTHING; -- IF ROW violates CONSTRAINT, will be skipped


-- Insert author 3
WITH author_3_data AS (
    SELECT 
        book_isbn.book_isbn_id,
        author.author_id,
        role.role_id
    FROM books_staging
    JOIN book_isbn ON (book_isbn.isbn10 = books_staging.isbn10 OR book_isbn.isbn13 = books_staging.isbn13)
    JOIN author ON author.full_name = books_staging.author_3
    LEFT JOIN role ON role.role = books_staging.author_3_role
    WHERE books_staging.author_3 IS NOT NULL
)
INSERT INTO author_isbn (book_isbn_id, author_id, role_id)
SELECT DISTINCT book_isbn_id, author_id, role_id
FROM author_3_data
ON CONFLICT (book_isbn_id, author_id, role_id) DO NOTHING;

-- Insert author 4
WITH author_4_data AS (
    SELECT 
        book_isbn.book_isbn_id,
        author.author_id,
        role.role_id
    FROM books_staging
    JOIN book_isbn ON (book_isbn.isbn10 = books_staging.isbn10 OR book_isbn.isbn13 = books_staging.isbn13)
    JOIN author ON author.full_name = books_staging.author_4
    LEFT JOIN role ON role.role = books_staging.author_4_role
    WHERE books_staging.author_4 IS NOT NULL
)
INSERT INTO author_isbn (book_isbn_id, author_id, role_id)
SELECT DISTINCT book_isbn_id, author_id, role_id
FROM author_4_data
ON CONFLICT (book_isbn_id, author_id, role_id) DO NOTHING;

-- Insert author 5
WITH author_5_data AS (
    SELECT 
        book_isbn.book_isbn_id,
        author.author_id,
        role.role_id
    FROM books_staging
    JOIN book_isbn ON (book_isbn.isbn10 = books_staging.isbn10 OR book_isbn.isbn13 = books_staging.isbn13)
    JOIN author ON author.full_name = books_staging.author_5
    LEFT JOIN role ON role.role = books_staging.author_5_role
    WHERE books_staging.author_5 IS NOT NULL
)
INSERT INTO author_isbn (book_isbn_id, author_id, role_id)
SELECT DISTINCT book_isbn_id, author_id, role_id
FROM author_5_data
ON CONFLICT (book_isbn_id, author_id, role_id) DO NOTHING;

*/

SELECT * FROM author_isbn;

SELECT 
    author_isbn.author_isbn_id,
    author.full_name as author,
    book_isbn.isbn13,
    role.role
FROM author_isbn
JOIN author ON author.author_id = author_isbn.author_id
JOIN book_isbn ON book_isbn.book_isbn_id = author_isbn.book_isbn_id
LEFT JOIN role ON role.role_id = author_isbn.role_id;



/*-----------------------------------------------*/
/* Review_Type */
/* look up table for review types! */
/*-----------------------------------------------*/
/*
CREATE TABLE IF NOT EXISTS review_type (
    review_type_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    review_type TEXT UNIQUE NOT NULL
);

INSERT INTO review_type (review_type)
VALUES 
    ('5_star'),
    ('4_star'),
    ('3_star'),
    ('2_star'),
    ('1_star');

*/

SELECT * FROM review_type

SELECT * FROM books_staging;


/*-----------------------------------------------*/
/* ISBN_Rating */
/*-----------------------------------------------*/
/*
CREATE TABLE IF NOT EXISTS isbn_rating (
    isbn_rating_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    book_isbn_id INT NOT NULL,
    review_type_id INT NOT NULL,
    count INT NOT NULL DEFAULT 0,
    
    CONSTRAINT fk_book_isbn
        FOREIGN KEY (book_isbn_id)
        REFERENCES book_isbn (book_isbn_id)
        ON DELETE CASCADE,
    
    CONSTRAINT fk_review_type
        FOREIGN KEY (review_type_id)
        REFERENCES review_type (review_type_id)
        ON DELETE CASCADE,
    
    CONSTRAINT uq_book_isbn_review_type UNIQUE (book_isbn_id, review_type_id)
);

-- Insert 5 star ratings (review_type_id = 1)
INSERT INTO isbn_rating (book_isbn_id, review_type_id, count)
SELECT
    book_isbn.book_isbn_id,
    1,  -- Hardcoded: 5_star
    books_staging."5_star"::INT
FROM books_staging
JOIN book_isbn ON (book_isbn.isbn10 = books_staging.isbn10 OR book_isbn.isbn13 = books_staging.isbn13)
WHERE books_staging."5_star" IS NOT NULL;

-- Insert 4 star ratings (review_type_id = 2)
INSERT INTO isbn_rating (book_isbn_id, review_type_id, count)
SELECT
    book_isbn.book_isbn_id,
    2,  -- Hardcoded: 4_star
    books_staging."4_star"::INT
FROM books_staging
JOIN book_isbn ON (book_isbn.isbn10 = books_staging.isbn10 OR book_isbn.isbn13 = books_staging.isbn13)
WHERE books_staging."4_star" IS NOT NULL
ON CONFLICT (book_isbn_id, review_type_id) DO NOTHING;

-- Insert 3 star ratings (review_type_id = 3)
INSERT INTO isbn_rating (book_isbn_id, review_type_id, count)
SELECT
    book_isbn.book_isbn_id,
    3,  -- Hardcoded: 3_star
    books_staging."3_star"::INT
FROM books_staging
JOIN book_isbn ON (book_isbn.isbn10 = books_staging.isbn10 OR book_isbn.isbn13 = books_staging.isbn13)
WHERE books_staging."3_star" IS NOT NULL
ON CONFLICT (book_isbn_id, review_type_id) DO NOTHING;

-- Insert 2 star ratings (review_type_id = 4)
INSERT INTO isbn_rating (book_isbn_id, review_type_id, count)
SELECT
    book_isbn.book_isbn_id,
    4,  -- Hardcoded: 2_star
    books_staging."2_star"::INT
FROM books_staging
JOIN book_isbn ON (book_isbn.isbn10 = books_staging.isbn10 OR book_isbn.isbn13 = books_staging.isbn13)
WHERE books_staging."2_star" IS NOT NULL
ON CONFLICT (book_isbn_id, review_type_id) DO NOTHING;

-- Insert 1 star ratings (review_type_id = 5)
INSERT INTO isbn_rating (book_isbn_id, review_type_id, count)
SELECT
    book_isbn.book_isbn_id,
    5,  -- Hardcoded: 1_star
    books_staging."1_star"::INT
FROM books_staging
JOIN book_isbn ON (book_isbn.isbn10 = books_staging.isbn10 OR book_isbn.isbn13 = books_staging.isbn13)
WHERE books_staging."1_star" IS NOT NULL
ON CONFLICT (book_isbn_id, review_type_id) DO NOTHING;
*/

SELECT * FROM isbn_rating ORDER BY book_isbn_id

SELECT 
    book_isbn.isbn13,
    review_type.review_type,
    isbn_rating.count
FROM isbn_rating
JOIN book_isbn ON book_isbn.book_isbn_id = isbn_rating.book_isbn_id
JOIN review_type ON review_type.review_type_id = isbn_rating.review_type_id
LIMIT 50;



/*-----------------------------------------------*/
/* Book_ISBN_Genre Table */
/*-----------------------------------------------*/
/*
CREATE TABLE IF NOT EXISTS book_isbn_genre (
    book_isbn_genre_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    book_isbn_id INT NOT NULL,
    genre_id INT NOT NULL,
    
    CONSTRAINT fk_book_isbn
        FOREIGN KEY (book_isbn_id)
        REFERENCES book_isbn (book_isbn_id)
        ON DELETE CASCADE,
    
    CONSTRAINT fk_genre
        FOREIGN KEY (genre_id)
        REFERENCES genre (genre_id)
        ON DELETE CASCADE,
    
    CONSTRAINT uq_book_isbn_genre UNIQUE (book_isbn_id, genre_id)
);

-- Insert genre 1
INSERT INTO book_isbn_genre (book_isbn_id, genre_id)
SELECT
    book_isbn.book_isbn_id,
    genre.genre_id
FROM books_staging
JOIN book_isbn ON (book_isbn.isbn10 = books_staging.isbn10 OR book_isbn.isbn13 = books_staging.isbn13)
JOIN genre ON genre.genre = books_staging.genre_1
WHERE books_staging.genre_1 IS NOT NULL;

-- Insert genre 2
INSERT INTO book_isbn_genre (book_isbn_id, genre_id)
SELECT
    book_isbn.book_isbn_id,
    genre.genre_id
FROM books_staging
JOIN book_isbn ON (book_isbn.isbn10 = books_staging.isbn10 OR book_isbn.isbn13 = books_staging.isbn13)
JOIN genre ON genre.genre = books_staging.genre_2
WHERE books_staging.genre_2 IS NOT NULL
ON CONFLICT (book_isbn_id, genre_id) DO NOTHING;

-- Insert genre 3
INSERT INTO book_isbn_genre (book_isbn_id, genre_id)
SELECT
    book_isbn.book_isbn_id,
    genre.genre_id
FROM books_staging
JOIN book_isbn ON (book_isbn.isbn10 = books_staging.isbn10 OR book_isbn.isbn13 = books_staging.isbn13)
JOIN genre ON genre.genre = books_staging.genre_3
WHERE books_staging.genre_3 IS NOT NULL
ON CONFLICT (book_isbn_id, genre_id) DO NOTHING;

-- Insert genre 4
INSERT INTO book_isbn_genre (book_isbn_id, genre_id)
SELECT
    book_isbn.book_isbn_id,
    genre.genre_id
FROM books_staging
JOIN book_isbn ON (book_isbn.isbn10 = books_staging.isbn10 OR book_isbn.isbn13 = books_staging.isbn13)
JOIN genre ON genre.genre = books_staging.genre_4
WHERE books_staging.genre_4 IS NOT NULL
ON CONFLICT (book_isbn_id, genre_id) DO NOTHING;

-- Insert genre 5
INSERT INTO book_isbn_genre (book_isbn_id, genre_id)
SELECT
    book_isbn.book_isbn_id,
    genre.genre_id
FROM books_staging
JOIN book_isbn ON (book_isbn.isbn10 = books_staging.isbn10 OR book_isbn.isbn13 = books_staging.isbn13)
JOIN genre ON genre.genre = books_staging.genre_5
WHERE books_staging.genre_5 IS NOT NULL
ON CONFLICT (book_isbn_id, genre_id) DO NOTHING;

-- Insert genre 6
INSERT INTO book_isbn_genre (book_isbn_id, genre_id)
SELECT
    book_isbn.book_isbn_id,
    genre.genre_id
FROM books_staging
JOIN book_isbn ON (book_isbn.isbn10 = books_staging.isbn10 OR book_isbn.isbn13 = books_staging.isbn13)
JOIN genre ON genre.genre = books_staging.genre_6
WHERE books_staging.genre_6 IS NOT NULL
ON CONFLICT (book_isbn_id, genre_id) DO NOTHING;

-- Insert genre 7
INSERT INTO book_isbn_genre (book_isbn_id, genre_id)
SELECT
    book_isbn.book_isbn_id,
    genre.genre_id
FROM books_staging
JOIN book_isbn ON (book_isbn.isbn10 = books_staging.isbn10 OR book_isbn.isbn13 = books_staging.isbn13)
JOIN genre ON genre.genre = books_staging.genre_7
WHERE books_staging.genre_7 IS NOT NULL
ON CONFLICT (book_isbn_id, genre_id) DO NOTHING;

-- Insert genre 8
INSERT INTO book_isbn_genre (book_isbn_id, genre_id)
SELECT
    book_isbn.book_isbn_id,
    genre.genre_id
FROM books_staging
JOIN book_isbn ON (book_isbn.isbn10 = books_staging.isbn10 OR book_isbn.isbn13 = books_staging.isbn13)
JOIN genre ON genre.genre = books_staging.genre_8
WHERE books_staging.genre_8 IS NOT NULL
ON CONFLICT (book_isbn_id, genre_id) DO NOTHING;

-- Insert genre 9
INSERT INTO book_isbn_genre (book_isbn_id, genre_id)
SELECT
    book_isbn.book_isbn_id,
    genre.genre_id
FROM books_staging
JOIN book_isbn ON (book_isbn.isbn10 = books_staging.isbn10 OR book_isbn.isbn13 = books_staging.isbn13)
JOIN genre ON genre.genre = books_staging.genre_9
WHERE books_staging.genre_9 IS NOT NULL
ON CONFLICT (book_isbn_id, genre_id) DO NOTHING;

-- Insert genre 10
INSERT INTO book_isbn_genre (book_isbn_id, genre_id)
SELECT
    book_isbn.book_isbn_id,
    genre.genre_id
FROM books_staging
JOIN book_isbn ON (book_isbn.isbn10 = books_staging.isbn10 OR book_isbn.isbn13 = books_staging.isbn13)
JOIN genre ON genre.genre = books_staging.genre_10
WHERE books_staging.genre_10 IS NOT NULL
ON CONFLICT (book_isbn_id, genre_id) DO NOTHING;

*/

SELECT * FROM book_isbn_genre LIMIT 100;

SELECT
    book_isbn.isbn13,
    book_isbn.isbn10,
    genre.genre
FROM book_isbn_genre
JOIN book_isbn ON book_isbn.book_isbn_id = book_isbn_genre.book_isbn_id
JOIN genre ON genre.genre_id = book_isbn_genre.genre_id
ORDER BY isbn13, isbn10;


/*-----------------------------------------------*/
/* Include series_id and series_num to book_isbn */
/*-----------------------------------------------*/
/*
ALTER TABLE book_isbn
ADD COLUMN series_id INT,
ADD COLUMN series_num NUMERIC(10,2),
ADD CONSTRAINT fk_series
    FOREIGN KEY (series_id)
    REFERENCES series (series_id)
    ON DELETE SET NULL;

SELECT * FROM book_isbn

UPDATE book_isbn
SET 
    series_id = series.series_id,
    series_num = books_staging.series_num::NUMERIC(10,2)
FROM books_staging
JOIN series ON series.series_name = books_staging.series_name_norm
WHERE (book_isbn.isbn10 = books_staging.isbn10 OR book_isbn.isbn13 = books_staging.isbn13)
  AND books_staging.series_name_norm IS NOT NULL;
*/

SELECT 
    book_isbn.isbn13,
    series.series_name,
    book_isbn.series_num
FROM book_isbn
LEFT JOIN series ON series.series_id = book_isbn.series_id
WHERE book_isbn.series_id IS NOT NULL
ORDER BY series.series_name, book_isbn.series_num;

SELECT * FROM book_isbn WHERE series_id is NULL;
SELECT * FROM book_isbn;
SELECT * FROM series;
SELECT * FROM books_staging;

SELECT
    book_isbn.isbn13,
    book.title,
    series.series_name,
    book_isbn.series_num
FROM book_isbn
LEFT JOIN series ON series.series_id = book_isbn.series_id
LEFT JOIN book ON book.book_id = book_isbn.book_id
ORDER BY title;

/*-----------------------------------------------*/
/* Add page number to book_isbn! */
/*-----------------------------------------------*/
/*
ALTER TABLE book_isbn
ADD COLUMN pages INT;

UPDATE book_isbn
SET pages = books_staging.pages_norm::INT
FROM books_staging
WHERE (book_isbn.isbn10 = books_staging.isbn10 OR book_isbn.isbn13 = books_staging.isbn13)
  AND books_staging.pages_norm IS NOT NULL
  AND TRIM(books_staging.pages_norm) != '';
*/

SELECT 
    isbn13,
    pages,
    is_boxset
FROM book_isbn
WHERE pages IS NOT NULL;

SELECT 
    book_isbn.isbn13,
    series.series_name,
    book_isbn.series_num
FROM book_isbn
LEFT JOIN series ON series.series_id = book_isbn.series_id
WHERE book_isbn.series_id IS NOT NULL
ORDER BY series.series_name, book_isbn.series_num;

SELECT * FROM book_isbn WHERE series_id is NULL;
SELECT * FROM book_isbn;
SELECT * FROM series;
SELECT * FROM books_staging;

SELECT
    book_isbn.isbn13,
    book.title,
    series.series_name,
    book_isbn.series_num
FROM book_isbn
LEFT JOIN series ON series.series_id = book_isbn.series_id
LEFT JOIN book ON book.book_id = book_isbn.book_id
ORDER BY title;

SELECT * FROM books_staging;
SELECT * FROM sales_fact;


SELECT 
    book_isbn.isbn13,
    book.title,
    author.full_name AS primary_author
FROM book_isbn
LEFT JOIN book ON book_isbn.book_id = book.book_id
LEFT JOIN author_isbn ON book_isbn.book_isbn_id = author_isbn.book_isbn_id
LEFT JOIN author ON author_isbn.author_id = author.author_id
WHERE book_isbn.is_boxset = True;


/*-----------------------------------------------*/
/* Adding updated at attribute to all tables */
/*-----------------------------------------------*/

/*
ALTER TABLE book ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE author ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE publisher ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE format ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE edition ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE language ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE series ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE genre ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE role ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE book_isbn ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE book_isbn_genre ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE author_isbn ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE review_type ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE isbn_rating ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
*/





