/*-----------------------------------------------------------*/
  /*     Star Schema Triggers + Logs + Stored Procs		*/
/*-----------------------------------------------------------*/


SELECT * FROM synthetic_sales;
SELECT * FROM book_dim;


-- create table synthetic_insert
-- keeps historyical data + tracks whats being uploaded to datawarehouse
/*
CREATE TABLE synthetic_insert (
    synthetic_insert_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    isbn13 TEXT,
    month INT NOT NULL,
    year INT NOT NULL,
    in_person_sales INT,
    online_sales INT,
    wholesale_sales INT,
    total_sales INT,
    average_price NUMERIC(10,2),
    total_revenue NUMERIC(10,2),
    count_returns INT,
    net_sales INT,
    nyt_best_selling_category TEXT,
    loaded_to_warehouse BOOLEAN DEFAULT FALSE, 
    CONSTRAINT unique_synthetic_insert UNIQUE (isbn13, month, year)
);

-- for performace, index for finding unloaded records
CREATE INDEX idx_synthetic_insert_loaded ON synthetic_insert(loaded_to_warehouse)  WHERE loaded_to_warehouse = FALSE;


INSERT INTO synthetic_insert (
    isbn13, month, YEAR, in_person_sales, online_sales, wholesale_sales, total_sales,
    average_price, total_revenue, count_returns, net_sales, nyt_best_selling_category, loaded_to_warehouse
)
SELECT 
    book_dim.isbn_13, month_year_dim.month, month_year_dim.year,
    sales_fact.in_person_sales, sales_fact.online_sales, sales_fact.wholesale_sales, sales_fact.total_sales,
    sales_fact.average_price, sales_fact.total_revenue, sales_fact.count_returns, sales_fact.net_sales,
    nyt_bestseller_dim.listed_as_desc,
    TRUE  -- Already loaded to warehouse
FROM sales_fact
JOIN book_dim ON book_dim.book_dim_id = sales_fact.book_dim_id
JOIN month_year_dim ON month_year_dim.month_year_dim_id = sales_fact.month_year_dim_id
LEFT JOIN nyt_bestseller_dim ON nyt_bestseller_dim.nyt_bestseller_dim_id = sales_fact.nyt_bestseller_dim_id
ON CONFLICT (isbn13, month, year) DO NOTHING;

*/

SELECT * FROM synthetic_insert;

-- synthetic_orphan_table
-- https://blog.devgenius.io/how-to-handle-orphan-data-in-fact-tables-7633d5f5a99

CREATE TABLE synthetic_unmatched (
    unmatched_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    isbn13 TEXT NOT NULL, month INT NOT NULL, year INT NOT NULL,
    in_person_sales INT, online_sales INT, wholesale_sales INT,
    total_sales INT, average_price NUMERIC(10,2), total_revenue NUMERIC(10,2),
    count_returns INT, net_sales INT, nyt_best_selling_category TEXT,
    notes TEXT,  
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_synthetic_unmatched UNIQUE (isbn13, month, year)
);



/*-----------------------------------------------*/
/* etl_log table */
-- https://stackoverflow.com/questions/63264139/best-practice-for-logging-mechanisam-in-etl-processing 
/*-----------------------------------------------*/

/*
CREATE TABLE etl_log (
    etl_log_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    run_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    source TEXT,  -- 'synthetic' or 'oltp'
    details TEXT,  -- 'update_month_year_dim', 'load_sales_to_warehouse', etc.
    rows_from_raw_data INT,
    rows_inserted_to_dw INT,
    rows_updated INT,
    rows_failed INT
);


INSERT INTO etl_log (source, details, rows_from_raw_data, rows_inserted_to_dw,rows_updated,rows_failed) 
	VALUES 
    ('synthetic', 'load_sales_fact', 
	     (SELECT COUNT(*) FROM sales_fact), 
	     (SELECT COUNT(*) FROM sales_fact), 
	     0, 0),
    ('oltp', 'load_book_dim', 
	     (SELECT COUNT(*) FROM book_dim), 
	     (SELECT COUNT(*) FROM book_dim), 
	     0, 0),
    ('oltp', 'load_author_dim', 
	     (SELECT COUNT(*) FROM author_dim), 
	     (SELECT COUNT(*) FROM author_dim), 
	     0, 0),
    ('synthetic', 'load_month_year_dim', 
	     (SELECT COUNT(*) FROM month_year_dim), 
	     (SELECT COUNT(*) FROM month_year_dim), 
	     0, 0);

*/

SELECT * FROM etl_log;


SELECT * FROM synthetic_insert;


/*-----------------------------------------------------------*/
  			/*      Stored Procs		*/
/*-----------------------------------------------------------*/

/*-----------------------------------------------*/
/* STORED PROC: updating month_year_dim */
-- help from AI (incorporated stackoverflow suggestions + AI)
-- prompt: what would be good attributes to include in log table (dim tables)?
/*-----------------------------------------------*/

SELECT * FROM etl_log;
SELECT * FROM month_year_dim ORDER BY YEAR, month;

/*
CREATE OR REPLACE PROCEDURE update_month_year_dim()
LANGUAGE plpgsql
AS $$
DECLARE
    v_rows_inserted INT := 0;
    v_rows_failed INT := 0;
    v_total_rows INT := 0;
BEGIN
    -- Count total distinct month/year combos to process
    SELECT COUNT(DISTINCT (month, year))
    INTO v_total_rows
    FROM synthetic_insert
    WHERE loaded_to_warehouse = FALSE;
    
    -- Insert unique month/year combos into month_year_dim if they don't already exist
    WITH new_month_years AS (
        SELECT DISTINCT month, year
        FROM synthetic_insert
        WHERE loaded_to_warehouse = FALSE
    )
    INSERT INTO month_year_dim (month, year)
    SELECT month, year
    FROM new_month_years
    ON CONFLICT (month, year) DO NOTHING;  
    
    GET DIAGNOSTICS v_rows_inserted = ROW_COUNT; 
    
    -- Log the result
    INSERT INTO etl_log (
        source,
        details,
        rows_from_raw_data,
        rows_inserted_to_dw,
        rows_updated,
        rows_failed
    )
    VALUES (
        'synthetic',
        'update_month_year_dim',
        v_total_rows,
        v_rows_inserted,
        0,
        v_rows_failed
    );
        
EXCEPTION
    WHEN OTHERS THEN -- help from AI to get exception
        -- Log failure
        INSERT INTO etl_log (
            source,
            details,
            rows_from_raw_data,
            rows_inserted_to_dw,
            rows_updated,
            rows_failed
        )
        VALUES (
            'synthetic',
            'update_month_year_dim',
            v_total_rows,
            0,
            0,
            1
        );
        RAISE;
END;
$$;

*/


/*-----------------------------------------------*/
/* STORED PROC: updating author_dim */
-- help from AI and stackoverflow
/*-----------------------------------------------*/

/*
CREATE OR REPLACE PROCEDURE update_author_dim()
LANGUAGE plpgsql
AS $$
DECLARE
    v_rows_inserted INT := 0;
    v_rows_failed INT := 0;
    v_total_rows INT := 0;
    v_last_etl_run TIMESTAMP;
BEGIN
    -- Get last ETL run date 
    SELECT MAX(run_date)
    INTO v_last_etl_run
    FROM etl_log
    WHERE source = 'oltp' AND details = 'update_author_dim';
    
    -- Count total authors updated since last run
    SELECT COUNT(*)
    INTO v_total_rows
    FROM author
    WHERE updated_at > v_last_etl_run;
    
    -- Insert new/updated authors into author_dim
    WITH new_authors AS (
        SELECT author_id, full_name
        FROM author
        WHERE updated_at > v_last_etl_run
    )
    INSERT INTO author_dim (author_id, author_name)
    SELECT author_id, full_name
    FROM new_authors
    ON CONFLICT (author_id) DO UPDATE
    SET author_name = EXCLUDED.author_name;
    
    GET DIAGNOSTICS v_rows_inserted = ROW_COUNT;
    
    -- Log the result
    INSERT INTO etl_log (
        source,
        details,
        rows_from_raw_data,
        rows_inserted_to_dw,
        rows_updated,
        rows_failed
    )
    VALUES (
        'oltp',
        'update_author_dim',
        v_total_rows,
        v_rows_inserted,
        0,
        v_rows_failed
    );
    
EXCEPTION
    WHEN OTHERS THEN
        INSERT INTO etl_log (
            source,
            details,
            rows_from_raw_data,
            rows_inserted_to_dw,
            rows_updated,
            rows_failed
        )
        VALUES (
            'oltp',
            'update_author_dim',
            v_total_rows,
            0,
            0,
            1
        );
        RAISE;
END;
$$;
*/




/*-----------------------------------------------*/
/* STORED PROC: updating nyt_bestseller_dim */
-- help from AI
/*-----------------------------------------------*/
/*
CREATE OR REPLACE PROCEDURE update_nyt_bestseller_dim()
LANGUAGE plpgsql
AS $$
DECLARE
    v_rows_inserted INT := 0;
    v_rows_failed INT := 0;
    v_total_rows INT := 0;
BEGIN
    -- Count total distinct nyt_best_selling_category
    SELECT COUNT(DISTINCT nyt_best_selling_category)
    INTO v_total_rows
    FROM synthetic_insert
    WHERE loaded_to_warehouse = FALSE;

    -- Insert unique NYT categories into nyt_bestseller_dim
    WITH new_nyt_best_selling_category AS (
        SELECT DISTINCT nyt_best_selling_category
        FROM synthetic_insert
        WHERE loaded_to_warehouse = FALSE
    )
    INSERT INTO nyt_bestseller_dim (listed_as_desc)
    SELECT nyt_best_selling_category
    FROM new_nyt_best_selling_category
    ON CONFLICT (listed_as_desc) DO NOTHING;
    
    GET DIAGNOSTICS v_rows_inserted = ROW_COUNT;
    
    -- Log the result
    INSERT INTO etl_log (
        source,
        details,
        rows_from_raw_data,
        rows_inserted_to_dw,
        rows_updated,
        rows_failed
    )
    VALUES (
        'synthetic',
        'update_nyt_bestseller_dim',
        v_total_rows,
        v_rows_inserted,
        0,
        v_rows_failed
    );
    
EXCEPTION
    WHEN OTHERS THEN
        INSERT INTO etl_log (
            source,
            details,
            rows_from_raw_data,
            rows_inserted_to_dw,
            rows_updated,
            rows_failed
        )
        VALUES (
            'synthetic',
            'update_nyt_bestseller_dim',
            v_total_rows,
            0,
            0,
            1
        );
        RAISE;
END;
$$;
*/

/*-----------------------------------------------*/
/* STORED PROC: updating update_book_dim */
-- help from AI
/*-----------------------------------------------*/

/*
CREATE OR REPLACE PROCEDURE update_book_dim()
LANGUAGE plpgsql
AS $$
DECLARE
    v_rows_inserted INT := 0;
    v_rows_failed INT := 0;
    v_total_rows INT := 0;
    v_last_etl_run TIMESTAMP;
BEGIN
    -- Get the last time we ran this ETL process
    -- This helps us only process books that are new or changed since last run
    SELECT MAX(run_date)
    INTO v_last_etl_run
    FROM etl_log
    WHERE source = 'oltp' AND details = 'update_book_dim';
    
    -- Count how many books have been updated since last ETL run
    -- This gives us a total to track in our log
    SELECT COUNT(*)
    INTO v_total_rows
    FROM book_isbn
    WHERE updated_at > v_last_etl_run;
    
    -- Insert NEW books from OLTP into the data warehouse book_dim
    -- We join to multiple tables to get all the book details
    WITH new_books AS (
        SELECT 
            book_isbn.book_isbn_id,      -- Unique identifier for this ISBN
            book.title AS book_title,     -- Book title from book table
            book_isbn.isbn13 AS isbn_13,  -- ISBN-13 number
            publisher.publisher,          -- Publisher name (can change → SCD Type 2)
            format.format,                -- Format (hardcover, paperback, etc.)
            language.language             -- Language of the book
        FROM book_isbn
        -- Get the book title
        JOIN book ON book.book_id = book_isbn.book_id
        -- Get publisher name (LEFT JOIN in case it's NULL)
        LEFT JOIN publisher ON book_isbn.publisher_id = publisher.publisher_id
        -- Get format name
        LEFT JOIN format ON book_isbn.format_id = format.format_id
        -- Get language name
        LEFT JOIN language ON book_isbn.language_id = language.language_id
        -- Only get books that changed since last ETL run
        WHERE book_isbn.updated_at > v_last_etl_run
    )
    -- Insert into book_dim
    -- Only insert if this book_isbn_id doesn't already exist
    INSERT INTO book_dim (
        book_isbn_id,
        book_title,
        isbn_13,
        publisher,
        format,
        language,
        effective_date,    -- When this record became effective (today)
        expire_date,       -- When it expires (NULL = current)
        current_flag       -- TRUE = this is the current record
    )
    SELECT 
        book_isbn_id,
        book_title,
        isbn_13,
        publisher,
        format,
        language,
        CURRENT_DATE,      -- Effective today
        NULL,              -- Not expired yet
        TRUE               -- This is the current version
    FROM new_books
    -- Only insert if this book_isbn_id doesn't already exist in book_dim
    WHERE NOT EXISTS (
        SELECT 1 
        FROM book_dim bd 
        WHERE bd.book_isbn_id = new_books.book_isbn_id
    );
    
    -- Track how many rows we actually inserted
    GET DIAGNOSTICS v_rows_inserted = ROW_COUNT;
    
    -- Log this ETL run to our etl_log table
    -- This helps us track what happened and when
    INSERT INTO etl_log (
        source,                    -- Where data came from ('oltp')
        details,                   -- What process ran
        rows_from_raw_data,        -- How many rows we looked at
        rows_inserted_to_dw,       -- How many we actually inserted
        rows_updated,              -- How many we updated (0 for this proc)
        rows_failed                -- How many failed (0 if successful)
    )
    VALUES (
        'oltp',
        'update_book_dim',
        v_total_rows,
        v_rows_inserted,
        0,
        v_rows_failed
    );
    
-- If anything goes wrong, catch the error and log it
EXCEPTION
    WHEN OTHERS THEN
        -- Log the failure
        INSERT INTO etl_log (
            source,
            details,
            rows_from_raw_data,
            rows_inserted_to_dw,
            rows_updated,
            rows_failed
        )
        VALUES (
            'oltp',
            'update_book_dim',
            v_total_rows,
            0,
            0,
            1  -- Mark as failed
        );
        -- Re-raise the error so we know something went wrong
        RAISE;
END;
$$;

*/


/*-----------------------------------------------*/
/* Trigger for SCD Type 2 */
-- help from AI
/*-----------------------------------------------*/

/*

CREATE OR REPLACE FUNCTION handle_publisher_rebrand()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_rows_changed INT;  
BEGIN
    IF TG_OP = 'UPDATE' AND OLD.publisher != NEW.publisher THEN
        
        -- Expire old records
        UPDATE book_dim
        SET
            expire_date = CURRENT_DATE,
            current_flag = FALSE
        WHERE
            publisher = OLD.publisher
            AND current_flag = TRUE;

        -- Insert new versions with updated publisher name
        INSERT INTO book_dim (
            book_isbn_id,
            book_title,
            isbn_13,
            publisher,
            format,
            language,
            effective_date,
            expire_date,
            current_flag
        )
        SELECT
            book_isbn_id,
            book_title,
            isbn_13,
            NEW.publisher,
            format,
            language,
            CURRENT_DATE,
            NULL,
            TRUE
        FROM book_dim
        WHERE
            publisher = OLD.publisher
            AND expire_date = CURRENT_DATE
            AND current_flag = FALSE;

        GET DIAGNOSTICS v_rows_changed = ROW_COUNT;

        -- Log the rebrand
        INSERT INTO etl_log (
            source,
            details,
            rows_from_raw_data,
            rows_inserted_to_dw,
            rows_updated,
            rows_failed
        ) VALUES (
            'oltp',
            'publisher_update',
            v_rows_changed,  
            v_rows_changed, 
            0,
            0
        );

    END IF;

    RETURN NEW;
END;
$$;


CREATE TRIGGER trigger_publisher_rebrand
AFTER UPDATE ON publisher
FOR EACH ROW
EXECUTE FUNCTION handle_publisher_rebrand();


*/

/*-----------------------------------------------*/
/* Stored proc for sales data into dw */
/*-----------------------------------------------*/

/*
 WITH ranked_authors AS (
        SELECT
            book_isbn.book_isbn_id,
            book_isbn.isbn13,
            author_isbn.author_id,
            ROW_NUMBER() OVER ( -- window function assigns 1, 2, 3, 4, 5
                PARTITION BY book_isbn.book_isbn_id -- counting starts over each different book
                ORDER BY author_isbn.author_isbn_id -- authors in order of author_isbn_id
            ) as author_num
        FROM book_isbn -- from book isbn in oltp
        JOIN author_isbn ON author_isbn.book_isbn_id = book_isbn.book_isbn_id
    ),
    pivoted_authors AS (
        SELECT
            book_isbn_id,
            isbn13,
            MAX(CASE WHEN author_num = 1 THEN author_id END) as author_id_1,
            MAX(CASE WHEN author_num = 2 THEN author_id END) as author_id_2,
            MAX(CASE WHEN author_num = 3 THEN author_id END) as author_id_3,
            MAX(CASE WHEN author_num = 4 THEN author_id END) as author_id_4,
            MAX(CASE WHEN author_num = 5 THEN author_id END) as author_id_5
        FROM ranked_authors
        GROUP BY book_isbn_id, isbn13
    )
    SELECT * FROM pivoted_authors;
 */

CREATE OR REPLACE PROCEDURE load_sales_to_warehouse(p_month INT, p_year INT)
LANGUAGE plpgsql
AS $$
DECLARE
    v_rows_inserted INT := 0;
    v_total_rows INT := 0;
BEGIN

    SELECT COUNT(*) -- count records
    INTO v_total_rows -- into our variable
    FROM synthetic_insert -- from synthetic table
    WHERE month = p_month -- when month is paramater month
      AND year = p_year -- and year is parameter year
      AND loaded_to_warehouse = FALSE; -- and data has not been loaded into DW
    
    -- Insert into sales_fact
    WITH ranked_authors AS (
        SELECT
            book_isbn.book_isbn_id,
            book_isbn.isbn13,
            author_isbn.author_id,
            ROW_NUMBER() OVER ( -- window function assigns 1, 2, 3, 4, 5
                PARTITION BY book_isbn.book_isbn_id -- counting starts over each different book
                ORDER BY author_isbn.author_isbn_id -- authors in order of author_isbn_id
            ) as author_num
        FROM book_isbn -- from book isbn in oltp
        JOIN author_isbn ON author_isbn.book_isbn_id = book_isbn.book_isbn_id
    ),
    pivoted_authors AS (
        SELECT
            book_isbn_id, isbn13,
			-- Pivot: convert author rows into columns
            MAX(CASE WHEN author_num = 1 THEN author_id END) as author_id_1,
            MAX(CASE WHEN author_num = 2 THEN author_id END) as author_id_2,
            MAX(CASE WHEN author_num = 3 THEN author_id END) as author_id_3,
            MAX(CASE WHEN author_num = 4 THEN author_id END) as author_id_4,
            MAX(CASE WHEN author_num = 5 THEN author_id END) as author_id_5
        FROM ranked_authors
        GROUP BY book_isbn_id, isbn13)
    INSERT INTO sales_fact (
        month_year_dim_id,
        book_dim_id,
        nyt_bestseller_dim_id,
        author_dim_id_1,
        author_dim_id_2,
        author_dim_id_3,
        author_dim_id_4,
        author_dim_id_5,
        in_person_sales,
        online_sales,
        wholesale_sales,
        total_sales,
        average_price,
        total_revenue,
        count_returns,
        net_sales,
		avg_rating
    )
    SELECT
        month_year_dim.month_year_dim_id,
        book_dim.book_dim_id,
        nyt_bestseller_dim.nyt_bestseller_dim_id,
        pivoted_authors.author_id_1,
        pivoted_authors.author_id_2,
        pivoted_authors.author_id_3,
        pivoted_authors.author_id_4,
        pivoted_authors.author_id_5,
        synthetic_insert.in_person_sales,
        synthetic_insert.online_sales,
        synthetic_insert.wholesale_sales,
        synthetic_insert.total_sales,
        synthetic_insert.average_price,
        synthetic_insert.total_revenue,
        synthetic_insert.count_returns,
        synthetic_insert.net_sales,
		(
        SELECT -- help from AI! 
            ((five_star.count * 5.0) + -- five star is alias for isbn rating table and count is the column
             (four_star.count * 4.0) + 
             (three_star.count * 3.0) + 
             (two_star.count * 2.0) + 
             (one_star.count * 1.0)) / 
            NULLIF((five_star.count + four_star.count + three_star.count + two_star.count + one_star.count), 0)
        FROM book_isbn 
        LEFT JOIN isbn_rating AS five_star ON five_star.book_isbn_id = book_isbn.book_isbn_id AND five_star.review_type_id = 1
        LEFT JOIN isbn_rating AS four_star ON four_star.book_isbn_id = book_isbn.book_isbn_id AND four_star.review_type_id = 2
        LEFT JOIN isbn_rating AS three_star ON three_star.book_isbn_id = book_isbn.book_isbn_id AND three_star.review_type_id = 3
        LEFT JOIN isbn_rating AS two_star ON two_star.book_isbn_id = book_isbn.book_isbn_id AND two_star.review_type_id = 4
        LEFT JOIN isbn_rating AS one_star ON one_star.book_isbn_id = book_isbn.book_isbn_id AND one_star.review_type_id = 5
        WHERE book_isbn.isbn13 = synthetic_insert.isbn13
    ) AS avg_rating
    FROM synthetic_insert
    JOIN book_dim ON book_dim.isbn_13 = synthetic_insert.isbn13 
        AND book_dim.current_flag = TRUE
    JOIN pivoted_authors ON pivoted_authors.isbn13 = synthetic_insert.isbn13
    JOIN month_year_dim ON month_year_dim.month = p_month 
        AND month_year_dim.year = p_year
    LEFT JOIN nyt_bestseller_dim ON nyt_bestseller_dim.listed_as_desc = synthetic_insert.nyt_best_selling_category
    WHERE synthetic_insert.month = p_month
      AND synthetic_insert.year = p_year
      AND synthetic_insert.loaded_to_warehouse = FALSE;
    
	-- https://www.postgresql.org/docs/current/plpgsql-statements.html
    GET DIAGNOSTICS v_rows_inserted = ROW_COUNT; -- postgres has GET DIAGNOSTICS with different  availble diagnostics 
    
  
    UPDATE synthetic_insert
    SET loaded_to_warehouse = TRUE
    WHERE month = p_month
      AND year = p_year
      AND loaded_to_warehouse = FALSE;
    
    -- Log the result
    INSERT INTO etl_log (
        source,
        details,
        rows_from_raw_data,
        rows_inserted_to_dw,
        rows_updated,
        rows_failed
    ) VALUES (
        'synthetic',
        'load_sales_to_warehouse',
        v_total_rows,
        v_rows_inserted,
        0,
        0
    );
    
EXCEPTION
    WHEN OTHERS THEN -- https://www.pgtutorial.com/plpgsql/plpgsql-exception/
        INSERT INTO etl_log (
            source,
            details,
            rows_from_raw_data,
            rows_inserted_to_dw,
            rows_updated,
            rows_failed) 
			VALUES (
            'synthetic',
            'load_sales_to_warehouse',
            v_total_rows,
            0,
            0,
            1
        );
        RAISE;
END;
$$;




/*-----------------------------------------------*/
/* Main Caller */
/*-----------------------------------------------*/

/*
CREATE OR REPLACE PROCEDURE process_monthly_sales(p_month INT, p_year INT)
LANGUAGE plpgsql
AS $$
BEGIN
    CALL update_month_year_dim(); -- update months and years into month_year dim
    CALL update_nyt_bestseller_dim(); -- any new listed_as_desc
    CALL update_author_dim(); -- any new authors
    CALL update_book_dim(); -- any new books
    
    -- Load to warehouse 
    CALL load_sales_to_warehouse(p_month, p_year);
    
    -- Master log entry
    INSERT INTO etl_log (
        source,
        details,
        rows_from_raw_data,
        rows_inserted_to_dw,
        rows_updated,
        rows_failed
    ) VALUES (
        'synthetic',
        'insert_monthly_sales',
        0,
        0,
        0,
        0
    );
    
EXCEPTION
    WHEN OTHERS THEN
        INSERT INTO etl_log (
            source,
            details,
            rows_from_raw_data,
            rows_inserted_to_dw,
            rows_updated,
            rows_failed
        ) VALUES (
            'synthetic',
            'insert_monthly_sales',
            0,
            0,
            0,
            1
        );
        RAISE;
END;
$$;

*/



/*-----------------------------------------------*/
/* TESTING */
/*-----------------------------------------------*/

-- insert new data
INSERT INTO synthetic_insert (
    isbn13,
    month,
    year,
    in_person_sales,
    online_sales,
    wholesale_sales,
    total_sales,
    average_price,
    total_revenue,
    count_returns,
    net_sales,
    nyt_best_selling_category,
    loaded_to_warehouse
)
VALUES
    ('9780316096157', 1, 2026, 100, 200, 150, 450, 25.99, 11695.50, 5, 445, 'Best Hardcover', FALSE),
    ('9780446545242', 1, 2026, 120, 180, 140, 440, 18.99, 8355.60, 3, 437, 'Best Paperback', FALSE),
    ('9780316101875', 1, 2026, 90, 210, 160, 460, 22.50, 10350.00, 7, 453, 'Best Hardcover', FALSE),
    ('9781585004782', 1, 2026, 110, 190, 130, 430, 19.99, 8595.70, 4, 426, 'Best E-Book', FALSE),
    ('9780316014793', 1, 2026, 95, 195, 145, 435, 24.99, 10870.65, 6, 429, 'Best Hardcover', FALSE),
    ('9780316431316', 1, 2026, 105, 205, 155, 465, 21.99, 10225.35, 8, 457, 'Best Paperback', FALSE),
    ('9780316523967', 1, 2026, 115, 185, 135, 435, 26.99, 11740.65, 5, 430, 'Best Hardcover', FALSE),
    ('9780316101844', 1, 2026, 130, 170, 150, 450, 20.99, 9445.50, 4, 446, 'Best E-Book', FALSE),
    ('9780446609401', 1, 2026, 100, 200, 140, 440, 17.99, 7915.60, 6, 434, 'Best Mass Market Books', FALSE),
    ('9780316018784', 1, 2026, 125, 175, 145, 445, 23.99, 10675.55, 7, 438, 'Best Hardcover', FALSE),
    ('9780316014779', 1, 2026, 110, 190, 155, 455, 22.99, 10460.45, 5, 450, 'Best Paperback', FALSE),
    ('9780316097468', 1, 2026, 105, 195, 160, 460, 19.99, 9195.40, 8, 452, 'Best E-Book', FALSE),
    ('9780316159791', 1, 2026, 120, 180, 135, 435, 25.99, 11305.65, 4, 431, 'Best Hardcover', FALSE),
    ('9780316128520', 1, 2026, 95, 205, 150, 450, 21.99, 9895.50, 6, 444, 'Best Paperback', FALSE),
    ('9780316036191', 1, 2026, 115, 185, 140, 440, 24.99, 10995.60, 7, 433, 'Best Hardcover', FALSE),
    ('9780316018746', 1, 2026, 100, 200, 145, 445, 18.99, 8450.55, 5, 440, 'Best E-Book', FALSE),
    ('9780316206938', 1, 2026, 110, 190, 155, 455, 26.99, 12280.45, 8, 447, 'Best Hardcover', FALSE),
    ('9780316018708', 1, 2026, 125, 175, 130, 430, 20.99, 9025.70, 3, 427, 'Best Paperback', FALSE),
    ('9780316013932', 1, 2026, 105, 195, 160, 460, 23.99, 11035.40, 6, 454, 'Best Hardcover', FALSE);


-- run all stored procs!
CALL process_monthly_sales(1, 2026);


-- check logs
SELECT 
    etl_log_id,
    run_date,
    source,
    details,
    rows_from_raw_data,
    rows_inserted_to_dw,
    rows_failed
FROM etl_log
WHERE run_date >= CURRENT_DATE
ORDER BY run_date DESC;


-- All January 2026 records should be loaded now
SELECT * FROM synthetic_insert WHERE month = 1 AND year = 2026;


SELECT * 
FROM sales_fact;

/*
INSERT INTO synthetic_insert (
    isbn13,
    month,
    year,
    in_person_sales,
    online_sales,
    wholesale_sales,
    total_sales,
    average_price,
    total_revenue,
    count_returns,
    net_sales,
    nyt_best_selling_category,
    loaded_to_warehouse
)
VALUES
    ('9780375856488', 1, 2026, 110, 190, 145, 445, 24.99, 11120.55, 5, 440, 'Best Hardcover', FALSE),
    ('9780802137982', 1, 2026, 95, 205, 150, 450, 21.99, 9895.50, 6, 444, 'Best Paperback', FALSE),
    ('9780552154765', 1, 2026, 120, 180, 140, 440, 19.99, 8795.60, 4, 436, 'Best E-Book', FALSE),
    ('9780609803875', 1, 2026, 105, 195, 155, 455, 26.99, 12280.45, 7, 448, 'Best Hardcover', FALSE);

*/

CALL process_monthly_sales(1, 2026);

SELECT * FROM sales_fact  JOIN month_year_dim ON sales_fact.month_year_dim_id = month_year_dim.month_year_dim_id 
WHERE month_year_dim.month = 1 AND month_year_dim.year = 2026;


SELECT COUNT(*) FROM synthetic_insert WHERE month = 1 AND year = 2026 AND loaded_to_warehouse = TRUE;


SELECT * FROM publisher WHERE publisher = 'two dollar radio';


SELECT 
    book_dim.book_dim_id,
    book_dim.book_isbn_id,
    book_dim.book_title,
    book_dim.isbn_13,
    book_dim.publisher,      
    book_dim.format,         
    book_dim.language,       
    book_dim.effective_date,
    book_dim.expire_date,
    book_dim.current_flag
FROM book_dim 
WHERE book_dim.current_flag = TRUE  -- Only current records
ORDER BY book_dim.book_dim_id DESC
LIMIT 20;


-- checking SCD type 2

SELECT * FROM book_dim WHERE publisher = 'two dollar radio' AND current_flag = TRUE;

UPDATE publisher SET publisher = 'two dollar radio publishing'WHERE publisher = 'two dollar radio';

SELECT  book_dim_id, book_title, publisher, effective_date, expire_date, current_flag
FROM book_dim WHERE publisher IN ('two dollar radio', 'two dollar radio publishing')
ORDER BY book_title, effective_date;


SELECT * FROM book_dim WHERE publisher IN ('two dollar radio', 'two dollar radio publishing');












