
/*
select 
	book.title,
	author.full_name, 
	synthetic_sales.* 
	FROM synthetic_sales
LEFT JOIN book_isbn ON synthetic_sales."ISBN" = book_isbn.isbn13
LEFT JOIN book ON book.book_id = book_isbn.book_id
LEFT JOIN author_isbn ON author_isbn.book_isbn_id = book_isbn.book_isbn_id
LEFT JOIN author ON author_isbn.author_id = author.author_id

ALTER TABLE synthetic_sales
ADD COLUMN title VARCHAR(255),
ADD COLUMN full_name VARCHAR(255);

UPDATE synthetic_sales
SET 
    title = book.title,
    full_name = author.full_name
FROM book_isbn
LEFT JOIN book ON book.book_id = book_isbn.book_id
LEFT JOIN author_isbn ON author_isbn.book_isbn_id = book_isbn.book_isbn_id
LEFT JOIN author ON author_isbn.author_id = author.author_id
WHERE synthetic_sales."ISBN" = book_isbn.isbn13;
*/

select * FROM synthetic_sales

/*
UPDATE synthetic_sales
SET "Month" = CASE TRIM("Month")
    WHEN 'Jan' THEN '1'
    WHEN 'Feb' THEN '2'
    WHEN 'Mar' THEN '3'
    WHEN 'Apr' THEN '4'
    WHEN 'May' THEN '5'
    WHEN 'Jun' THEN '6'
    WHEN 'Jul' THEN '7'
    WHEN 'Aug' THEN '8'
    WHEN 'Sep' THEN '9'
    WHEN 'Oct' THEN '10'
    WHEN 'Nov' THEN '11'
    WHEN 'Dec' THEN '12'
END;


-- Remove $ and commas from Average_Price
UPDATE synthetic_sales
SET "Average Price" = REPLACE(REPLACE(TRIM("Average Price"), '$', ''), ',', '');

-- Remove $ and commas from Total_Revenue
UPDATE synthetic_sales
SET "Total Revenue" = REPLACE(REPLACE(TRIM("Total Revenue"), '$', ''), ',', '');
*/

select 
	book.title,
	author.full_name, 
	synthetic_sales.* ,
	format.format
	FROM synthetic_sales
LEFT JOIN book_isbn ON synthetic_sales."ISBN" = book_isbn.isbn13
LEFT JOIN book ON book.book_id = book_isbn.book_id
LEFT JOIN author_isbn ON author_isbn.book_isbn_id = book_isbn.book_isbn_id
LEFT JOIN author ON author_isbn.author_id = author.author_id
LEFT JOIN format ON book_isbn.format_id = format.format_id 


WITH cte AS (
select 
	book.title,
	author.full_name, 
	synthetic_sales.* ,
	format.format
	FROM synthetic_sales
LEFT JOIN book_isbn ON synthetic_sales."ISBN" = book_isbn.isbn13
LEFT JOIN book ON book.book_id = book_isbn.book_id
LEFT JOIN author_isbn ON author_isbn.book_isbn_id = book_isbn.book_isbn_id
LEFT JOIN author ON author_isbn.author_id = author.author_id
LEFT JOIN format ON book_isbn.format_id = format.format_id )
SELECT DISTINCT format FROM cte


ALTER TABLE synthetic_sales
ADD COLUMN nyt_best_selling_category TEXT;

/*
UPDATE synthetic_sales
SET nyt_best_selling_category = CASE 
    WHEN format.format = 'paperback' THEN 'Best Paperback'
    WHEN format.format = 'unknown' THEN 'Best Paperback'
    WHEN format.format = 'board_book' THEN 'Best Childrens/Middle Grade Books'
    WHEN format.format = 'mass_market_paperback' THEN 'Best Mass Market Books'
    WHEN format.format = 'hardcover' THEN 'Best Hardcover'
    WHEN format.format = 'ebook' THEN 'Best E-Book'
    WHEN format.format = 'audio' THEN 'Best Audio'
    ELSE 'Best Paperback'  -- Default fallback
END
FROM book_isbn
LEFT JOIN format ON book_isbn.format_id = format.format_id
WHERE synthetic_sales."ISBN" = book_isbn.isbn13;
*/

-- Verify
SELECT 
    format.format,
    synthetic_sales.nyt_best_selling_category,
    COUNT(*) as count
FROM synthetic_sales
LEFT JOIN book_isbn ON synthetic_sales."ISBN" = book_isbn.isbn13
LEFT JOIN format ON book_isbn.format_id = format.format_id
GROUP BY format.format, synthetic_sales.nyt_best_selling_category
ORDER BY format.format;



/*-----------------------------------------------*/
/* Month-Year-Dim Table */
/*-----------------------------------------------*/

CREATE TABLE IF NOT EXISTS month_year_dim (
    month_year_dim_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    month INT NOT NULL,
    year INT NOT NULL,
    CONSTRAINT uq_month_year UNIQUE (month, year)
);
/*
INSERT INTO month_year_dim (month, year)
SELECT DISTINCT 
    "Month"::INT,
    "Year"::INT
FROM synthetic_sales
WHERE "Month" IS NOT NULL 
  AND "Year" IS NOT NULL
  AND TRIM("Month") != '' 
  AND TRIM("Year") != ''
ORDER BY "Year"::INT, "Month"::INT
ON CONFLICT (month, year) DO NOTHING;
*/

SELECT * FROM month_year_dim
ORDER BY year, month;

SELECT COUNT(*) FROM month_year_dim;



/*-----------------------------------------------*/
/* Author Dim Table */
/*-----------------------------------------------*/

/*
CREATE TABLE IF NOT EXISTS author_dim (
    author_dim_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    author_id INT NOT NULL UNIQUE,
    author_name TEXT NOT NULL
);

INSERT INTO author_dim (author_id, author_name)
SELECT 
    author_id,
    full_name
FROM author
ORDER BY author_id
ON CONFLICT (author_id) DO NOTHING;
*/

SELECT * FROM author_dim
ORDER BY author_dim_id;


/*-----------------------------------------------*/
/* Book_Dim Table */
/*-----------------------------------------------*/
/*
-- Create Book_Dim with SCD Type 2 structure
CREATE TABLE IF NOT EXISTS book_dim (
    book_dim_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    book_isbn_id INT NOT NULL,
    book_title TEXT,
    isbn_13 TEXT,
    publisher TEXT,
    format TEXT,
    language TEXT,
    effective_date DATE NOT NULL,
    expire_date DATE,
    current_flag BOOLEAN NOT NULL DEFAULT TRUE
);


INSERT INTO book_dim (
    book_isbn_id,
    book_title,
    isbn_13,
    publisher,
    format,
    language,
    effective_date,
    expire_date,
    current_flag
)
SELECT 
    book_isbn.book_isbn_id,
    book.title AS book_title,
    book_isbn.isbn13 AS isbn_13,
    publisher.publisher AS publisher,
    format.format AS format,
    language.language AS language,
    CURRENT_DATE AS effective_date,
    NULL AS expire_date,
    TRUE AS current_flag
FROM book_isbn
JOIN book ON book.book_id = book_isbn.book_id
LEFT JOIN publisher ON book_isbn.publisher_id = publisher.publisher_id
LEFT JOIN format ON book_isbn.format_id = format.format_id
LEFT JOIN language ON book_isbn.language_id = language.language_id;

*/

SELECT * FROM book_dim ORDER BY book_dim_id;



/*-----------------------------------------------*/
/* NYT_BestSeller_Dim */
/*-----------------------------------------------*/

/*
CREATE TABLE IF NOT EXISTS nyt_bestseller_dim (
    nyt_bestseller_dim_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    listed_as_desc TEXT NOT NULL UNIQUE
);

-- Populate it with unique values from synthetic_sales
INSERT INTO nyt_bestseller_dim (listed_as_desc)
SELECT DISTINCT nyt_best_selling_category
FROM synthetic_sales
WHERE nyt_best_selling_category IS NOT NULL
  AND TRIM(nyt_best_selling_category) != ''
ORDER BY nyt_best_selling_category
ON CONFLICT (listed_as_desc) DO NOTHING;

*/


SELECT * FROM nyt_bestseller_dim
ORDER BY listed_as_desc;

-- Count
SELECT COUNT(*) FROM nyt_bestseller_dim;


SELECT * FROM synthetic_sales ss 

/*-----------------------------------------------*/
/* TESTING Sales_Fact Dim */
/*-----------------------------------------------*/
/*
DROP TABLE IF EXISTS sales_fact

CREATE TABLE IF NOT EXISTS sales_fact (
    sales_fact_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    month_year_dim_id INT NOT NULL,
    author_dim_id_1 INT,  
    author_dim_id_2 INT,  
    author_dim_id_3 INT,  
    author_dim_id_4 INT,  
    author_dim_id_5 INT,  
    book_dim_id INT NOT NULL,
    nyt_bestseller_dim_id INT,
    in_person_sales INT,
    online_sales INT,
    wholesale_sales INT,
    total_sales INT,
    average_price NUMERIC(10,2),
    total_revenue NUMERIC(10,2),
    count_returns INT,
    net_sales INT
);
*/

SELECT * FROM synthetic_sales;
SELECT * FROM sales_fact;

-- testing
WITH synthetic_sales_isbn as(
SELECT "ISBN" AS isbn, "Month" AS MONTH, "Year" AS YEAR,
"In-Person Sales" AS in_person_sales,
"Online Sales" AS online_sales,
"Wholesale Sales" AS wholesale_sales,
"Total Sales" AS total_sales,
"Average Price" AS average_price,
"Total Revenue" AS total_venue,
"Returns" AS count_returns
FROM synthetic_sales
)
SELECT synthetic_sales_isbn.*, book_isbn.book_id, book_isbn.isbn13, author_isbn.author_id
FROM synthetic_sales_isbn JOIN book_isbn ON synthetic_sales_isbn.isbn = book_isbn.isbn13
JOIN author_isbn ON book_isbn.book_isbn_id  = author_isbn.book_isbn_id
WHERE book_isbn.isbn13 = '9781442359888'

-- test to see what to insert first
WITH synthetic_sales_isbn AS (
    SELECT 
        "ISBN" AS isbn, 
        "Month" AS month, 
        "Year" AS year,
        "In-Person Sales" AS in_person_sales,
        "Online Sales" AS online_sales,
        "Wholesale Sales" AS wholesale_sales,
        "Total Sales" AS total_sales,
        "Average Price" AS average_price,
        "Total Revenue" AS total_revenue,
        "Returns" AS count_returns,
        "Net Sales" AS net_sales,
        nyt_best_selling_category AS listing
    FROM synthetic_sales
),
ranked_authors AS (
    SELECT 
        book_isbn.book_isbn_id,
        book_isbn.isbn13,
        author_isbn.author_id,
        ROW_NUMBER() OVER ( -- WINDOW FUNCTION, assigns numbers 1-5 TO ROWS BY 
            PARTITION BY book_isbn.book_isbn_id -- restart the numbering for each different book_isbn_id
            ORDER BY author_isbn.author_isbn_id
        ) as author_position
    FROM book_isbn
    JOIN author_isbn ON author_isbn.book_isbn_id = book_isbn.book_isbn_id
),
pivoted_authors AS (
    SELECT 
        book_isbn_id,
        isbn13,
        -- (Help from AI): For each book, MAX finds the one non-NULL value (the author_id where position = 1)
        MAX(CASE WHEN author_position = 1 THEN author_id END) as author_id_1,
        MAX(CASE WHEN author_position = 2 THEN author_id END) as author_id_2,
        MAX(CASE WHEN author_position = 3 THEN author_id END) as author_id_3,
        MAX(CASE WHEN author_position = 4 THEN author_id END) as author_id_4,
        MAX(CASE WHEN author_position = 5 THEN author_id END) as author_id_5
    FROM ranked_authors
    GROUP BY book_isbn_id, isbn13
)
SELECT
	month_year_dim.month_year_dim_id,
	book_dim.book_dim_id,
	nyt_bestseller_dim.nyt_bestseller_dim_id,
	pivoted_authors.author_id_1,
    pivoted_authors.author_id_2,
    pivoted_authors.author_id_3,
    pivoted_authors.author_id_4,
    pivoted_authors.author_id_5,
    synthetic_sales_isbn.in_person_sales,
    synthetic_sales_isbn.online_sales,
	synthetic_sales_isbn.wholesale_sales,
    synthetic_sales_isbn.total_sales,
    synthetic_sales_isbn.average_price,
    synthetic_sales_isbn.total_revenue,
    synthetic_sales_isbn.count_returns,
    synthetic_sales_isbn.net_sales
FROM synthetic_sales_isbn
JOIN book_dim ON synthetic_sales_isbn.isbn = book_dim.isbn_13
JOIN pivoted_authors ON pivoted_authors.book_isbn_id = book_dim.book_isbn_id
JOIN month_year_dim ON 
	month_year_dim.MONTH = synthetic_sales_isbn.month::INT
	AND month_year_dim.YEAR = synthetic_sales_isbn.year::INT
JOIN nyt_bestseller_dim ON nyt_bestseller_dim.listed_as_desc = synthetic_sales_isbn.listing
WHERE book_dim.current_flag = TRUE; 

SELECT * FROM synthetic_sales; -- CHECK IF counts MATCH 

/*-----------------------------------------------*/
/* Insert Sales_Fact Dim */
/*-----------------------------------------------*/
/*
INSERT INTO sales_fact (
    month_year_dim_id,
    book_dim_id,
    nyt_bestseller_dim_id,
    author_dim_id_1,
    author_dim_id_2,
    author_dim_id_3,
    author_dim_id_4,
    author_dim_id_5,
    in_person_sales,
    online_sales,
    wholesale_sales,
    total_sales,
    average_price,
    total_revenue,
    count_returns,
    net_sales
)
WITH synthetic_sales_isbn AS (
    SELECT
        "ISBN" AS isbn,
        "Month" AS month,
        "Year" AS year,
        "In-Person Sales" AS in_person_sales,
        "Online Sales" AS online_sales,
        "Wholesale Sales" AS wholesale_sales,
        "Total Sales" AS total_sales,
        "Average Price" AS average_price,
        "Total Revenue" AS total_revenue,
        "Returns" AS count_returns,
        "Net Sales" AS net_sales,
        nyt_best_selling_category AS listing
    FROM synthetic_sales
),
ranked_authors AS (
    SELECT
        book_isbn.book_isbn_id,
        book_isbn.isbn13,
        author_isbn.author_id,
        ROW_NUMBER() OVER (
            PARTITION BY book_isbn.book_isbn_id
            ORDER BY author_isbn.author_isbn_id
        ) as author_position
    FROM book_isbn
    JOIN author_isbn ON author_isbn.book_isbn_id = book_isbn.book_isbn_id
),
pivoted_authors AS (
    SELECT
        book_isbn_id,
        isbn13,
        MAX(CASE WHEN author_position = 1 THEN author_id END) as author_id_1,
        MAX(CASE WHEN author_position = 2 THEN author_id END) as author_id_2,
        MAX(CASE WHEN author_position = 3 THEN author_id END) as author_id_3,
        MAX(CASE WHEN author_position = 4 THEN author_id END) as author_id_4,
        MAX(CASE WHEN author_position = 5 THEN author_id END) as author_id_5
    FROM ranked_authors
    GROUP BY book_isbn_id, isbn13
)
SELECT
    month_year_dim.month_year_dim_id,
    book_dim.book_dim_id,
    nyt_bestseller_dim.nyt_bestseller_dim_id,
    pivoted_authors.author_id_1,
    pivoted_authors.author_id_2,
    pivoted_authors.author_id_3,
    pivoted_authors.author_id_4,
    pivoted_authors.author_id_5,
    synthetic_sales_isbn.in_person_sales::INT,
    synthetic_sales_isbn.online_sales::INT,
    synthetic_sales_isbn.wholesale_sales::INT,
    synthetic_sales_isbn.total_sales::INT,
    synthetic_sales_isbn.average_price::NUMERIC(10,2),
    synthetic_sales_isbn.total_revenue::NUMERIC(10,2),
    synthetic_sales_isbn.count_returns::INT,
    synthetic_sales_isbn.net_sales::INT
FROM synthetic_sales_isbn
JOIN book_dim ON synthetic_sales_isbn.isbn = book_dim.isbn_13
JOIN pivoted_authors ON pivoted_authors.book_isbn_id = book_dim.book_isbn_id
JOIN month_year_dim ON
    month_year_dim.month = synthetic_sales_isbn.month::INT
    AND month_year_dim.year = synthetic_sales_isbn.year::INT
JOIN nyt_bestseller_dim ON nyt_bestseller_dim.listed_as_desc = synthetic_sales_isbn.listing
WHERE book_dim.current_flag = TRUE;
*/

SELECT COUNT(*) FROM sales_fact;

SELECT * FROM sales_fact LIMIT 50;

-- Check statistics
SELECT 
    COUNT(*) as total_records,
    SUM(total_sales) as total_units_sold,
    SUM(total_revenue) as total_revenue,
    AVG(average_price)::NUMERIC(10,2) as avg_price
FROM sales_fact;

SELECT * FROM sales_fact ORDER BY in_person_sales DESC LIMIT 1;
SELECT * FROM sales_fact ORDER BY in_person_sales ASC LIMIT 1;


/* add rating to slaes_fact */

/*
ALTER TABLE sales_fact ADD COLUMN avg_rating NUMERIC(3,2); -- 3 total digits WITH 2 AFTER decimal ex: 4.02

UPDATE sales_fact
SET avg_rating = (
    SELECT 
        ((five_star.count * 5.0) + 
         (four_star.count * 4.0) + 
         (three_star.count * 3.0) + 
         (two_star.count * 2.0) + 
         (one_star.count * 1.0)) / 
        NULLIF((five_star.count + four_star.count + three_star.count + two_star.count + one_star.count), 0)
    FROM book_dim
    JOIN book_isbn ON book_dim.book_isbn_id = book_isbn.book_isbn_id
    -- since there are multiple conditions, i use filtered left join to get specific columns
    LEFT JOIN isbn_rating AS five_star ON five_star.book_isbn_id = book_isbn.book_isbn_id AND five_star.review_type_id = 1
    LEFT JOIN isbn_rating AS four_star ON four_star.book_isbn_id = book_isbn.book_isbn_id AND four_star.review_type_id = 2
    LEFT JOIN isbn_rating AS three_star ON three_star.book_isbn_id = book_isbn.book_isbn_id AND three_star.review_type_id = 3
    LEFT JOIN isbn_rating AS two_star ON two_star.book_isbn_id = book_isbn.book_isbn_id AND two_star.review_type_id = 4
    LEFT JOIN isbn_rating AS one_star ON one_star.book_isbn_id = book_isbn.book_isbn_id AND one_star.review_type_id = 5
    WHERE book_dim.book_dim_id = sales_fact.book_dim_id
);
*/









